dist: xenial
language: python
cache: pip
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- '3.7'
- '3.8'
before_install:
- pip install pycodestyle coverage codecov
- if [[ "$TRAVIS_PYTHON_VERSION" == 2.7* ]]; then pip install mock; fi
install:
- pip install virtualenv --upgrade
- make install
- make test-install
script:
- pycodestyle --exclude=venv
- coverage run -m unittest discover
after_script:
- codecov
- make test
- coverage run tests/test_unit.py
after_success:
- codecov
deploy:
  provider: pypi
  user: __token__
  password: "$PYPI_TOKEN"
  skip_cleanup: true
  on:
    branch: main
    condition: "$TRAVIS_TEST_RESULT = 0"
    tags: true
    python: '3.6'
notifications:
  slack:
    if: branch = main
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms:
      secure: iGjR8si8UTjr4hbuL5De3kw1V0DVcTRjednU06QZ4/O8lf+OuMG92Q5tgWkS+yKZd+U94QTycQnZC/KYLfnIn+0VBSsnhiAju8oNYSiFZGKn2AypNtGXJ0DWFmTViKQI2c/pquRQzAQJG6owjBudOURMZ8EYBZRByNqOD/xzvFnNfTLGzkjVAyWMBpRW78NqAl9w5ztIAPR98gGYdujBa73RLhV/CJ7aVYzq9UGyyZ/+NmUejAA5t86EgGci0vse5r50tOuyrECmN0LwtE+aIxYAH7b8bJHPE9+7LovxPscLz83pWCG27m3IxVAksGtxpQ8VFe1YsM3LOVFSml8N7O3V7C15f21rBNtZ2r7ufMHsjeERlbvm+fRlAB98UIpZEthmEodQ34xxudTO1uUN2J0lZDZ+NKCruozMCvF8B/bfSyVIf4AdeTQo0FIPcWj5hEAumw/dYr9zx/lrNil/Ssi7q5sBHXW811HPsl0Wc4qF34traFO9hoCtilOj3ULCSigXvEnJdDQvUSJBAbsQ3Xdj31ACsUwwpT6M1jSQ77FGncdEYMaTJQAMHqL/tiM+kKVaDOMzBSZwf/uTh1uHv6lnVHDGtQdxI2x5s326cFWkf0rcne5z6EXxP1YR4bbD3y1JaLxBE5+Hu+mvU8nSVpIyp9f7cgMHjIsuv7emllA=
